"use strict";
(function(){
const el=id=>document.getElementById(id);const state={target:null,stops:[]};
const esc=v=>String(v==null?"":v).replace(/[&<>"\x27]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\x27":"&#39;"}[c]));
const valid=p=>p&&p.lat!=null&&p.lng!=null&&Number.isFinite(+p.lat)&&Number.isFinite(+p.lng);
const label=p=>valid(p)?p.lat+","+p.lng:(p.navQuery||p.name||"");
const dKm=(a,b)=>{const r=x=>x*Math.PI/180,dl=r(b.lat-a.lat),do_=r(b.lng-a.lng),v=Math.sin(dl/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(do_/2)**2;return 12742*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
const azimuth=(a,b)=>{const r=x=>x*Math.PI/180,y=Math.sin(r(b.lng-a.lng))*Math.cos(r(b.lat)),x=Math.cos(r(a.lat))*Math.sin(r(b.lat))-Math.sin(r(a.lat))*Math.cos(r(b.lat))*Math.cos(r(b.lng-a.lng));return(Math.atan2(y,x)*180/Math.PI+360)%360};
const groupOptions=[["","すべて"],["cafe","カフェ・飲食"],["shop","バイクショップ"],["rest","ライダー休憩所"],["lodging","ライダー向け宿泊"],["service","整備・サービス"],["community","交流スポット"]];
const origin=()=>typeof origins!=="undefined"?origins.ride:null;
function spots(goalOnly=false){const data=window.APP_DATA||{};return [...(data.roads||[]).map(x=>({...x,tourGroup:"road"})),...(data.landmarks||[]).map(x=>({...x,tourGroup:x.level==="A"?"A":"B"})),...(window.RIDERS_CAFES||[]).filter(x=>(x.publish!==false||x.testOnly)&&(!goalOnly||(x.gachaDestinationEligible===true||(x.gachaDestinationEligible!==false&&["cafe","food","rest","community"].includes(x.spotCategory||"cafe"))))).map(x=>({...x,tourGroup:"riders"}))].filter(valid)}
function categoryOptions(group){return group==="riders"?groupOptions:(group==="A"||group==="B")&&typeof FEATURES!=="undefined"?FEATURES:[["","すべて"]]}
function fillCategory(groupId,categoryId){const group=el(groupId).value;el(categoryId).innerHTML=categoryOptions(group).map(x=>"<option value="+JSON.stringify(x[0])+">"+esc(x[1])+"</option>").join("")}
function changeGroup(){fillCategory("tourGroup","tourCategory")}
function changeNearGroup(){fillCategory("tourNearGroup","tourNearCategory");if(state.target)nearby()}
function byCategory(x,group,cat){return group==="riders"?(!cat||(x.spotCategory||"cafe")===cat):((group==="A"||group==="B")&&cat?featureMatch(x,cat):true)}
function dropOptions(list,selectId,placeholder,formatter){el(selectId).innerHTML='<option value="">'+esc(placeholder)+'</option>'+list.map((x,i)=>'<option value="'+i+'">'+esc(formatter(x))+'</option>').join("")}
function search(){const from=origin();if(!from){alert("先に出発地点を設定してください");return}const km=+el("tourDistance").value,tol=+el("tourTolerance").value;if(!(km>0&&km<=1000&&tol>=0&&tol<=300)){alert("距離の入力値を確認してください");return}const compass={north:0,east:90,south:180,west:270},dir=el("tourDirection").value,group=el("tourGroup").value,cat=el("tourCategory").value;const list=spots(true).filter(x=>group==="all"||x.tourGroup===group).filter(x=>byCategory(x,group,cat)).map(x=>({...x,tourKm:dKm(from,x),tourAz:azimuth(from,x)})).filter(x=>x.tourKm>=Math.max(0,km-tol)&&x.tourKm<=km+tol).filter(x=>dir==="all"||Math.abs((x.tourAz-compass[dir]+540)%360-180)<=33.75).sort((a,b)=>Math.abs(a.tourKm-km)-Math.abs(b.tourKm-km));window.tourCandidates=list;dropOptions(list,"tourTargetSelect","目標地点を選択してください",x=>x.name+" / "+(x.prefecture||"")+" / 直線"+x.tourKm.toFixed(1)+"km");el("tourCandidateCount").textContent="検索結果 "+list.length+"件（直線"+Math.max(0,km-tol)+"〜"+(km+tol)+"km）"}
function choose(i){const x=window.tourCandidates?.[i];if(!x)return;state.target={name:x.name,lat:x.lat,lng:x.lng,navQuery:x.navQuery||""};state.stops=[];const notice=el("tourTargetNotice");if(notice)notice.textContent="✅ 目標地点を「"+x.name+"」に設定しました。以下に目標地点から直線"+el("tourRadius").value+"km以内の追加候補を表示しています。";render();nearby()}
function nearby(){if(!state.target)return alert("目標地点を選択してください");const km=+el("tourRadius").value;if(!(km>=0&&km<=300))return alert("寄り道半径を確認してください");const group=el("tourNearGroup").value,cat=el("tourNearCategory").value;const list=spots().filter(x=>group==="all"||x.tourGroup===group).filter(x=>byCategory(x,group,cat)).filter(x=>dKm(x,state.target)<=km&&!(x.name===state.target.name&&x.lat===state.target.lat&&x.lng===state.target.lng)).sort((a,b)=>dKm(a,state.target)-dKm(b,state.target));window.tourNearList=list;dropOptions(list,"tourNearSelect","追加する寄り道地点を選択してください",x=>x.name+" / "+(x.prefecture||"")+" / 直線"+dKm(x,state.target).toFixed(1)+"km");el("tourNearCount").textContent="周辺候補 "+list.length+"件（目標地点から直線"+km+"km以内）"}
function add(x){if(!state.target)return alert("目標地点を選択してください");if(state.stops.length>=2)return alert("寄り道は最大2地点です");state.stops.push(x);render()}
function addNearby(i){const x=window.tourNearList?.[i];if(x)add({name:x.name,lat:x.lat,lng:x.lng,navQuery:x.navQuery||""})}
function chooseSelected(){const v=el("tourTargetSelect").value;if(v==="")return alert("目標地点を選択してください");choose(Number(v))}
function addNearbySelected(){const v=el("tourNearSelect").value;if(v==="")return alert("寄り道地点を選択してください");addNearby(Number(v))}
function remove(i){state.stops.splice(i,1);render()}
function render(){el("tourPlanState").innerHTML="<div>🎯 目標："+esc(state.target?.name||"未選択")+"</div>"+state.stops.map((x,i)=>"<div>☕ 寄り道"+(i+1)+"："+esc(x.name)+" <button class=\"soft\" onclick=\"tourRemove("+i+")\">削除</button></div>").join("")+"<div class=\"meta\">中間経由地 "+(state.target?1+state.stops.length:0)+"/3</div>"}
function changeReturn(){el("tourReturnExtra").hidden=el("tourReturnSame").checked}
function openMaps(){if(!origin()||!state.target)return alert("出発地点と目標地点を設定してください");const ret=el("tourReturnSame").checked?origin():(()=>{const v=el("tourReturnName").value.trim();return v?{name:v,navQuery:v}:(typeof origins!=="undefined"&&origins.tourReturn)||null})();if(!ret)return alert("帰着地点を指定してください");const params=new URLSearchParams({api:"1",origin:label(origin()),destination:label(ret),waypoints:[state.target,...state.stops].map(label).join("|"),travelmode:"driving"});if(el("tourVehicle").value==="125")params.set("avoid","highways,tolls");const url="https://www.google.com/maps/dir/?"+params;if(url.length>2048)return alert("地名が長すぎるためGoogleマップへ渡せません");window.open(url,"_blank","noopener")}
const PLAN_KEY="michino_touring_plans_v1";let activePlanId=null;
function allPlans(){try{const a=JSON.parse(localStorage.getItem(PLAN_KEY)||"[]");return Array.isArray(a)?a:[]}catch(e){return[]}}
function selectedReturn(){if(el("tourReturnSame").checked)return origin();const v=el("tourReturnName").value.trim();return v?{name:v,navQuery:v}:(typeof origins!=="undefined"&&origins.tourReturn)||null}
function planSnapshot(){if(!origin()||!state.target)return null;return{id:activePlanId||null,name:el("tourPlanName").value.trim()||"今日のツーリング",origin:{...origin()},target:{...state.target},stops:state.stops.map(x=>({...x})),returnSame:el("tourReturnSame").checked,returnPoint:el("tourReturnSame").checked?null:selectedReturn(),vehicle:el("tourVehicle").value,updatedAt:new Date().toISOString()}}
function savePlan(asNew=false){const plan=planSnapshot();if(!plan)return alert("出発地点と目標地点を設定してください");if(!plan.returnSame&&!plan.returnPoint)return alert("帰着地点を設定してください");const plans=allPlans();if(!asNew&&activePlanId){const i=plans.findIndex(x=>x.id===activePlanId);if(i>=0){plans[i]={...plan,id:activePlanId};localStorage.setItem(PLAN_KEY,JSON.stringify(plans));renderPlans();alert("計画を上書き保存しました");return}}if(plans.length>=30)return alert("保存できるツーリング計画は30件までです");plan.id=Date.now()+"-"+Math.random().toString(36).slice(2,7);activePlanId=plan.id;plans.unshift(plan);localStorage.setItem(PLAN_KEY,JSON.stringify(plans));renderPlans();alert("ツーリング計画を保存しました")}
function loadPlan(id){const p=allPlans().find(x=>x.id===id);if(!p)return;activePlanId=id;setOrigin("ride",p.origin.lat,p.origin.lng,p.origin.label||"保存した出発地");state.target={...p.target};state.stops=Array.isArray(p.stops)?p.stops.slice(0,2):[];el("tourPlanName").value=p.name||"";el("tourVehicle").value=p.vehicle||"250";el("tourReturnSame").checked=p.returnSame!==false;el("tourReturnName").value="";if(!p.returnSame&&p.returnPoint){if(valid(p.returnPoint))setOrigin("tourReturn",p.returnPoint.lat,p.returnPoint.lng,p.returnPoint.label||p.returnPoint.name||"保存した帰着地");else el("tourReturnName").value=p.returnPoint.navQuery||p.returnPoint.name||""}changeReturn();render();renderPlans();const notice=el("tourTargetNotice");if(notice)notice.textContent="✅ 保存した計画の目標地点「"+(state.target?.name||"未設定")+"」を読み込みました。";if(state.target)nearby();showView("ride")}
function deletePlan(id){if(!confirm("このツーリング計画を削除しますか？"))return;localStorage.setItem(PLAN_KEY,JSON.stringify(allPlans().filter(x=>x.id!==id)));if(activePlanId===id)activePlanId=null;renderPlans()}
function renderPlans(){const area=el("tourSavedPlans");if(!area)return;const plans=allPlans();area.innerHTML='<option value="">保存した計画を選択</option>'+plans.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+" / "+esc((p.updatedAt||"").slice(0,10))+'</option>').join("");if(activePlanId&&plans.some(p=>p.id===activePlanId))area.value=activePlanId}
function loadSelected(){const id=el("tourSavedPlans").value;if(id)loadPlan(id)}
function deleteSelected(){const id=el("tourSavedPlans").value;if(id)deletePlan(id)}
function sendToDetour(){if(!origin()||!state.target)return alert("先に出発地点と目標地点を指定してください");const snapshot=planSnapshot();if(!snapshot)return;window.tourImportToDetour?.(snapshot);showView("detour")}
function importFromDetour(){const chosen=window.tourExportFromDetour?.();if(!chosen)return alert("寄り道から取り込む地点がありません");if(chosen.length>2)return alert("寄り道は最大2地点です。寄り道しようで選択数を減らしてください");state.stops=chosen.map(p=>({name:p.name||"寄り道地点",lat:p.lat,lng:p.lng,navQuery:p.navQuery||""}));render();showView("ride");alert("寄り道"+chosen.length+"地点を反映しました。保存すると計画を更新できます。")}

window.tourGroupChanged=changeGroup;window.tourSavePlan=()=>savePlan(false);window.tourSavePlanAs=()=>savePlan(true);window.tourLoadSelected=loadSelected;window.tourDeleteSelected=deleteSelected;window.tourSendToDetour=sendToDetour;window.tourImportFromDetour=importFromDetour;window.tourNearGroupChanged=changeNearGroup;window.tourChooseSelected=chooseSelected;window.tourAddNearbySelected=addNearbySelected;window.tourSearch=search;window.tourChoose=choose;window.tourSearchNearby=nearby;window.tourAddNearby=addNearby;window.tourRemove=remove;window.tourReturnChanged=changeReturn;window.tourOpenMaps=openMaps;
document.addEventListener("DOMContentLoaded",()=>{if(el("tourGroup")){changeGroup();changeNearGroup();render();changeReturn();renderPlans()}});
})();
