"use strict";
(function(){
const el=id=>document.getElementById(id);const state={target:null,stops:[]};
const esc=v=>String(v==null?"":v).replace(/[&<>"\x27]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\x27":"&#39;"}[c]));
const valid=p=>p&&p.lat!=null&&p.lng!=null&&Number.isFinite(+p.lat)&&Number.isFinite(+p.lng);
const label=p=>valid(p)?p.lat+","+p.lng:(p.navQuery||p.name||"");
const dKm=(a,b)=>{const r=x=>x*Math.PI/180,dl=r(b.lat-a.lat),do_=r(b.lng-a.lng),v=Math.sin(dl/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(do_/2)**2;return 12742*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
const azimuth=(a,b)=>{const r=x=>x*Math.PI/180,y=Math.sin(r(b.lng-a.lng))*Math.cos(r(b.lat)),x=Math.cos(r(a.lat))*Math.sin(r(b.lat))-Math.sin(r(a.lat))*Math.cos(r(b.lat))*Math.cos(r(b.lng-a.lng));return(Math.atan2(y,x)*180/Math.PI+360)%360};
const groupOptions=[["","すべて"],["cafe","カフェ・飲食"],["shop","バイクショップ"],["rest","ライダー休憩所"],["lodging","ライダー向け宿泊"],["service","整備・サービス"],["community","交流スポット"]];
const origin=()=>typeof origins!=="undefined"?origins.ride:null;
function spots(goalOnly=false){const data=window.APP_DATA||{};return [...(data.roads||[]).map(x=>({...x,tourGroup:"road"})),...(data.landmarks||[]).map(x=>({...x,tourGroup:x.level==="A"?"A":"B"})),...(window.RIDERS_CAFES||[]).filter(x=>(x.publish!==false||x.testOnly)&&(!goalOnly||(x.gachaDestinationEligible===true||(x.gachaDestinationEligible!==false&&["cafe","food","rest","community"].includes(x.spotCategory||"cafe"))))).map(x=>({...x,tourGroup:"riders"}))].filter(valid)}
function categoryOptions(group){return group==="riders"?groupOptions:(group==="A"||group==="B")&&typeof FEATURES!=="undefined"?FEATURES:[["","すべて"]]}
function fillCategory(groupId,categoryId){const group=el(groupId).value;el(categoryId).innerHTML=categoryOptions(group).map(x=>"<option value="+JSON.stringify(x[0])+">"+esc(x[1])+"</option>").join("")}
function changeGroup(){fillCategory("tourGroup","tourCategory")}
function changeNearGroup(){fillCategory("tourNearGroup","tourNearCategory");if(state.target)nearby()}
function byCategory(x,group,cat){return group==="riders"?(!cat||(x.spotCategory||"cafe")===cat):((group==="A"||group==="B")&&cat?featureMatch(x,cat):true)}
function dropOptions(list,selectId,placeholder,formatter){el(selectId).innerHTML='<option value="">'+esc(placeholder)+'</option>'+list.map((x,i)=>'<option value="'+i+'">'+esc(formatter(x))+'</option>').join("")}
function search(){const from=origin();if(!from){alert("先に出発地点を設定してください");return}const km=+el("tourDistance").value,tol=+el("tourTolerance").value;if(!(km>0&&km<=1000&&tol>=0&&tol<=300)){alert("距離の入力値を確認してください");return}const compass={north:0,east:90,south:180,west:270},dir=el("tourDirection").value,group=el("tourGroup").value,cat=el("tourCategory").value;
const all=spots(true),eventRoads=group==="roadEvent"?all.filter(x=>x.tourGroup==="road"&&activeRoadEvents(x).length>0):[];
const matching=all.filter(x=>group==="all"||x.tourGroup===group||(group==="roadEvent"&&eventRoads.includes(x))).filter(x=>byCategory(x,group,cat));
const ranged=matching.map(x=>({...x,tourKm:dKm(from,x),tourAz:azimuth(from,x)})).filter(x=>x.tourKm>=Math.max(0,km-tol)&&x.tourKm<=km+tol);
const list=ranged.filter(x=>dir==="all"||Math.abs((x.tourAz-compass[dir]+540)%360-180)<=33.75).sort((a,b)=>Math.abs(a.tourKm-km)-Math.abs(b.tourKm-km));
window.tourCandidates=list;dropOptions(list,"tourTargetSelect","目標地点を選択してください",x=>x.name+" / "+(x.prefecture||"")+(group==="roadEvent"?" / "+activeRoadEvents(x).map(e=>e.startDate+" "+e.title).join("・"):"")+" / 直線"+x.tourKm.toFixed(1)+"km");
const total=roadEvents.filter(e=>e.endDate>=jpToday()&&e.status!=="cancelled").length;
const debug=group==="roadEvent"?" / 情報"+total+"件・照合"+eventRoads.length+"駅・距離内"+ranged.length+"駅"+(dir!=="all"?"・方角内"+list.length+"駅":""):"";
el("tourCandidateCount").textContent=(group==="roadEvent"&&!eventsReady?"⚠️ イベント情報が未取得です。イベント情報を更新してください。":"検索結果 "+list.length+"件（直線"+Math.max(0,km-tol)+"〜"+(km+tol)+"km）"+debug);
}
function choose(i){const x=window.tourCandidates?.[i];if(!x)return;state.target={name:x.name,lat:x.lat,lng:x.lng,navQuery:x.navQuery||""};state.stops=[];const notice=el("tourTargetNotice");if(notice)notice.textContent="✅ 目標地点を「"+x.name+"」に設定しました。以下に目標地点から直線"+el("tourRadius").value+"km以内の追加候補を表示しています。";render();nearby();const eventInfo=el("tourTargetEventNotice");if(eventInfo){const es=activeRoadEvents(x);eventInfo.hidden=es.length===0;eventInfo.innerHTML=es.length?"<b>📅 この道の駅の開催予定イベント</b>"+es.map(e=>"<div>"+esc(e.startDate)+(e.endDate!==e.startDate?"〜"+esc(e.endDate):"")+"："+esc(e.title)+(e.url?' <a href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">公式案内 ↗</a>':"")+"</div>").join(""):""}}
function nearby(){if(!state.target)return alert("目標地点を選択してください");const km=+el("tourRadius").value;if(!(km>=0&&km<=300))return alert("寄り道半径を確認してください");const group=el("tourNearGroup").value,cat=el("tourNearCategory").value;const list=spots().filter(x=>group==="all"||x.tourGroup===group).filter(x=>byCategory(x,group,cat)).filter(x=>dKm(x,state.target)<=km&&!(x.name===state.target.name&&x.lat===state.target.lat&&x.lng===state.target.lng)).sort((a,b)=>dKm(a,state.target)-dKm(b,state.target));window.tourNearList=list;dropOptions(list,"tourNearSelect","追加する寄り道地点を選択してください",x=>x.name+" / "+(x.prefecture||"")+" / 直線"+dKm(x,state.target).toFixed(1)+"km");el("tourNearCount").textContent="周辺候補 "+list.length+"件（目標地点から直線"+km+"km以内）"}
function add(x){if(!state.target)return alert("目標地点を選択してください");if(state.stops.length>=2)return alert("寄り道は最大2地点です");state.stops.push(x);render()}
function addNearby(i){const x=window.tourNearList?.[i];if(x)add({name:x.name,lat:x.lat,lng:x.lng,navQuery:x.navQuery||""})}
function chooseSelected(){const v=el("tourTargetSelect").value;if(v==="")return alert("目標地点を選択してください");choose(Number(v))}
function addNearbySelected(){const v=el("tourNearSelect").value;if(v==="")return alert("寄り道地点を選択してください");addNearby(Number(v))}
function remove(i){state.stops.splice(i,1);render()}
function render(){const mapButton=el("tourTargetMapBtn");if(mapButton)mapButton.hidden=!state.target;el("tourPlanState").innerHTML="<div>🎯 目標："+esc(state.target?.name||"未選択")+"</div>"+state.stops.map((x,i)=>"<div>☕ 寄り道"+(i+1)+"："+esc(x.name)+" <button class=\"soft tour-action tour-action-danger\" onclick=\"tourRemove("+i+")\">削除</button></div>").join("")+"<div class=\"meta\">中間経由地 "+(state.target?1+state.stops.length:0)+"/3</div>"+(state.target?'<button type="button" class="soft tour-action tour-action-map" onclick="tourPreviewRoute(true)">🗺️ 登録地点までのルート・走行距離を確認</button>':"")}
function previewRoute(includeStops=false){const from=origin(),target=state.target;if(!from||!target)return alert("出発地点と目標地点を設定してください");const path=includeStops?[target,...state.stops]:[target];const params=new URLSearchParams({api:"1",origin:label(from),destination:label(path[path.length-1]),travelmode:"driving"});if(path.length>1)params.set("waypoints",path.slice(0,-1).map(label).join("|"));if(el("tourVehicle").value==="125")params.set("avoid","highways,tolls");const url="https://www.google.com/maps/dir/?"+params.toString();if(url.length>2048)return alert("GoogleマップのURL上限を超えています");window.open(url,"_blank","noopener")}
function changeReturn(){el("tourReturnExtra").hidden=el("tourReturnSame").checked}
function openMaps(){if(!origin()||!state.target)return alert("出発地点と目標地点を設定してください");const ret=el("tourReturnSame").checked?origin():(()=>{const v=el("tourReturnName").value.trim();return v?{name:v,navQuery:v}:(typeof origins!=="undefined"&&origins.tourReturn)||null})();if(!ret)return alert("帰着地点を指定してください");const params=new URLSearchParams({api:"1",origin:label(origin()),destination:label(ret),waypoints:[state.target,...state.stops].map(label).join("|"),travelmode:"driving"});if(el("tourVehicle").value==="125")params.set("avoid","highways,tolls");const url="https://www.google.com/maps/dir/?"+params;if(url.length>2048)return alert("地名が長すぎるためGoogleマップへ渡せません");window.open(url,"_blank","noopener")}
const EVENT_URL="./data/road_events.json";let roadEvents=[];let eventsReady=false;
const jpToday=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const sameRoad=(x,e)=>{const norm=v=>String(v||"").normalize("NFKC").replace(/^道の駅[\s　「『]*(?:「|『)?/,"").replace(/[\s　・･「」『』（）()\-ー]/g,"").toLowerCase();const name=norm(x.name),event=norm(e.roadName);const pref=v=>String(v||"").replace(/[都道府県\s　]/g,"");return name===event&&(!e.prefecture||!x.prefecture||pref(x.prefecture)===pref(e.prefecture))};
const activeRoadEvents=x=>roadEvents.filter(e=>e&&e.roadName&&/^\d{4}-\d{2}-\d{2}$/.test(e.endDate||"")&&e.endDate>=jpToday()&&(!e.publishedAt||e.publishedAt<=jpToday())&&e.status!=="cancelled"&&sameRoad(x,e));
const EVENT_CACHE_KEY="michino_road_events_cache_v1";
const EVENT_CHECK_KEY="michino_road_events_checked_v1";
function eventDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||"")}
function sanitizeEvent(e){if(!e||typeof e!=="object")return null;const allowedUrl=typeof e.url==="string"&&/^https:\/\//i.test(e.url)?e.url:"";if(!e.roadName||!e.title||!eventDate(e.startDate)||!eventDate(e.endDate)||e.endDate<e.startDate)return null;return {roadName:String(e.roadName).slice(0,120),prefecture:String(e.prefecture||"").slice(0,30),title:String(e.title).slice(0,160),startDate:e.startDate,endDate:e.endDate,publishedAt:eventDate(e.publishedAt)?e.publishedAt:"",url:allowedUrl,status:e.status==="cancelled"?"cancelled":"scheduled"}}
function renderRoadEventList(){const list=el("tourEventList");if(!list||list.hidden)return;const events=roadEvents.filter(e=>e.endDate>=jpToday()&&e.status!=="cancelled").sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.prefecture.localeCompare(b.prefecture));if(!events.length){list.innerHTML='<p class="note">表示できるイベントはありません。必要なら「イベント情報を更新」を押してください。</p>';return}list.innerHTML='<p class="note">開催終了前のイベント '+events.length+'件（距離・方角による絞り込みなし）</p>'+events.map(e=>'<div class="panel" style="margin:8px 0;padding:12px"><strong>📍 '+esc(e.roadName)+'</strong> <span class="note">'+esc(e.prefecture)+'</span><div style="margin-top:5px">📅 '+esc(e.startDate)+(e.endDate!==e.startDate?' 〜 '+esc(e.endDate):'')+'</div><div style="margin-top:5px">'+esc(e.title)+'</div>'+(e.url?'<div style="margin-top:6px"><a href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">公式イベント案内 ↗</a></div>':'')+'</div>').join("")}
function toggleRoadEventList(){const list=el("tourEventList"),btn=el("tourEventListBtn");if(!list||!btn)return;list.hidden=!list.hidden;btn.setAttribute("aria-expanded",String(!list.hidden));btn.textContent=list.hidden?"📋 イベント情報を確認（一覧）":"📋 イベント一覧を閉じる";renderRoadEventList()}
function renderEventStatus(message){const e=el("tourEventStatus");if(!e)return;const checked=localStorage.getItem(EVENT_CHECK_KEY),active=roadEvents.filter(x=>x.endDate>=jpToday()&&x.status!=="cancelled").length;e.textContent=(message?message+" / ":"")+(checked?"最終取得："+new Date(checked).toLocaleString("ja-JP"):"未取得")+" / 登録 "+roadEvents.length+"件（終了前 "+active+"件）"}
function loadLocalRoadEvents(){try{const payload=JSON.parse(localStorage.getItem(EVENT_CACHE_KEY)||"null");roadEvents=Array.isArray(payload?.events)?payload.events.map(sanitizeEvent).filter(Boolean):[];eventsReady=!!payload}catch(e){roadEvents=[];eventsReady=false}renderEventStatus();renderRoadEventList()}
async function updateRoadEvents(){const btn=el("tourEventUpdateBtn");if(btn){btn.disabled=true;btn.textContent="⏳ イベント情報を取得中…"}try{const res=await fetch(EVENT_URL+"?t="+Date.now(),{cache:"no-store"});if(!res.ok)throw Error("HTTP "+res.status);const payload=await res.json();if(payload?.schemaVersion!==1||!Array.isArray(payload.events))throw Error("イベントJSONの形式が不正です");const cleaned=payload.events.map(sanitizeEvent);if(cleaned.some(x=>!x))throw Error("不正なイベント情報が含まれています");localStorage.setItem(EVENT_CACHE_KEY,JSON.stringify({events:cleaned}));localStorage.setItem(EVENT_CHECK_KEY,new Date().toISOString());roadEvents=cleaned;eventsReady=true;renderEventStatus("✅ 更新しました");renderRoadEventList();alert("イベント情報を更新しました！ 登録 "+roadEvents.length+"件。");if(el("tourGroup")?.value==="roadEvent")searchSilently()}catch(e){console.warn("イベント情報の取得失敗",e);renderEventStatus("⚠️ 取得失敗："+String(e.message||e).slice(0,100)+"。以前のデータを使用中");alert("イベント情報の取得に失敗しました。\n"+String(e.message||e)+"\n通信状態を確認して再度お試しください。")}finally{if(btn){btn.disabled=false;btn.textContent="🔄 イベント情報を更新"}}}
function searchSilently(){if(origin())search();else if(el("tourCandidateCount"))el("tourCandidateCount").textContent="出発地点を決めるとイベント開催予定の道の駅を検索できます"}
const PLAN_KEY="michino_touring_plans_v1";let activePlanId=null;
function allPlans(){try{const a=JSON.parse(localStorage.getItem(PLAN_KEY)||"[]");return Array.isArray(a)?a:[]}catch(e){return[]}}
function selectedReturn(){if(el("tourReturnSame").checked)return origin();const v=el("tourReturnName").value.trim();return v?{name:v,navQuery:v}:(typeof origins!=="undefined"&&origins.tourReturn)||null}
function planSnapshot(){if(!origin()||!state.target)return null;return{id:activePlanId||null,name:el("tourPlanName").value.trim()||"今日のツーリング",origin:{...origin()},target:{...state.target},stops:state.stops.map(x=>({...x})),returnSame:el("tourReturnSame").checked,returnPoint:el("tourReturnSame").checked?null:selectedReturn(),vehicle:el("tourVehicle").value,updatedAt:new Date().toISOString()}}
function savePlan(asNew=false){const plan=planSnapshot();if(!plan)return alert("出発地点と目標地点を設定してください");if(!plan.returnSame&&!plan.returnPoint)return alert("帰着地点を設定してください");const plans=allPlans();if(!asNew&&activePlanId){const i=plans.findIndex(x=>x.id===activePlanId);if(i>=0){plans[i]={...plan,id:activePlanId};localStorage.setItem(PLAN_KEY,JSON.stringify(plans));renderPlans();alert("計画を上書き保存しました");return}}if(plans.length>=30)return alert("保存できるツーリング計画は30件までです");plan.id=Date.now()+"-"+Math.random().toString(36).slice(2,7);activePlanId=plan.id;plans.unshift(plan);localStorage.setItem(PLAN_KEY,JSON.stringify(plans));renderPlans();alert("ツーリング計画を保存しました")}
function loadPlan(id){const p=allPlans().find(x=>x.id===id);if(!p)return;activePlanId=id;setOrigin("ride",p.origin.lat,p.origin.lng,p.origin.label||"保存した出発地");state.target={...p.target};state.stops=Array.isArray(p.stops)?p.stops.slice(0,2):[];el("tourPlanName").value=p.name||"";el("tourVehicle").value=p.vehicle||"250";el("tourReturnSame").checked=p.returnSame!==false;el("tourReturnName").value="";if(!p.returnSame&&p.returnPoint){if(valid(p.returnPoint))setOrigin("tourReturn",p.returnPoint.lat,p.returnPoint.lng,p.returnPoint.label||p.returnPoint.name||"保存した帰着地");else el("tourReturnName").value=p.returnPoint.navQuery||p.returnPoint.name||""}changeReturn();render();renderPlans();const notice=el("tourTargetNotice");if(notice)notice.textContent="✅ 保存した計画の目標地点「"+(state.target?.name||"未設定")+"」を読み込みました。";if(state.target)nearby();showView("ride")}
function deletePlan(id){if(!confirm("このツーリング計画を削除しますか？"))return;localStorage.setItem(PLAN_KEY,JSON.stringify(allPlans().filter(x=>x.id!==id)));if(activePlanId===id)activePlanId=null;renderPlans()}
function renderPlans(){const area=el("tourSavedPlans");if(!area)return;const plans=allPlans();area.innerHTML='<option value="">保存した計画を選択</option>'+plans.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+" / "+esc((p.updatedAt||"").slice(0,10))+'</option>').join("");if(activePlanId&&plans.some(p=>p.id===activePlanId))area.value=activePlanId}
function renderFavoritePlans(){const node=el("tourFavoriteList");if(!node)return;const plans=allPlans();node.innerHTML=plans.length?plans.map((p,i)=>'<div class="fav-card"><div class="fav-top"><div><span class="pill">ツーリング計画</span><h3>'+esc(p.name||"今日のツーリング")+'</h3></div></div><div class="meta">スタート：'+esc(p.origin?.label||"出発地点")+' → 目標：'+esc(p.target?.name||"未設定")+' / 追加 '+(p.stops?.length||0)+'件<br>帰着：'+esc(p.returnSame!==false?"出発地点と同じ":p.returnPoint?.label||p.returnPoint?.name||"別指定")+' / 保存日 '+esc((p.updatedAt||"").slice(0,10))+'</div><div class="actions"><button type="button" class="soft" onclick="tourOpenFavoritePlan('+i+')">✏️ 今日の走り方で編集</button><button type="button" class="soft" onclick="tourMapFavoritePlan('+i+')">🗺 Googleマップで確認</button></div></div>').join(""):'<div class="note">保存したツーリング計画はまだありません。</div>'}
function openFavoritePlan(i){const p=allPlans()[i];if(p)loadPlan(p.id)}
function mapFavoritePlan(i){const p=allPlans()[i];if(!p?.origin||!p.target)return alert("ルート情報が不足しています");const path=[p.target,...(p.stops||[])].slice(0,3);const destination=p.returnSame!==false?p.origin:p.returnPoint;if(!destination)return alert("帰着地点が未設定です");const params=new URLSearchParams({api:"1",origin:label(p.origin),destination:label(destination),waypoints:path.map(label).join("|"),travelmode:"driving"});if(p.vehicle==="125")params.set("avoid","highways,tolls");const url="https://www.google.com/maps/dir/?"+params.toString();if(url.length>2048)return alert("Googleマップ連携URLが長すぎます");window.open(url,"_blank","noopener")}
function loadSelected(){const id=el("tourSavedPlans").value;if(id)loadPlan(id)}
function deleteSelected(){const id=el("tourSavedPlans").value;if(id)deletePlan(id)}
function sendToDetour(){if(!origin()||!state.target)return alert("先に出発地点と目標地点を指定してください");const snapshot=planSnapshot();if(!snapshot)return;window.tourImportToDetour?.(snapshot);showView("detour")}
function importFromDetour(){const chosen=window.tourExportFromDetour?.();if(!chosen)return alert("寄り道から取り込む地点がありません");if(chosen.length>2)return alert("寄り道は最大2地点です。寄り道しようで選択数を減らしてください");state.stops=chosen.map(p=>({name:p.name||"寄り道地点",lat:p.lat,lng:p.lng,navQuery:p.navQuery||""}));render();showView("ride");alert("寄り道"+chosen.length+"地点を反映しました。保存すると計画を更新できます。")}

window.tourPreviewRoute=previewRoute;window.tourToggleEventList=toggleRoadEventList;window.tourUpdateRoadEvents=updateRoadEvents;window.tourRenderFavoritePlans=renderFavoritePlans;window.tourOpenFavoritePlan=openFavoritePlan;window.tourMapFavoritePlan=mapFavoritePlan;window.tourGroupChanged=changeGroup;window.tourSavePlan=()=>savePlan(false);window.tourSavePlanAs=()=>savePlan(true);window.tourLoadSelected=loadSelected;window.tourDeleteSelected=deleteSelected;window.tourSendToDetour=sendToDetour;window.tourImportFromDetour=importFromDetour;window.tourNearGroupChanged=changeNearGroup;window.tourChooseSelected=chooseSelected;window.tourAddNearbySelected=addNearbySelected;window.tourSearch=search;window.tourChoose=choose;window.tourSearchNearby=nearby;window.tourAddNearby=addNearby;window.tourRemove=remove;window.tourReturnChanged=changeReturn;window.tourOpenMaps=openMaps;
document.addEventListener("DOMContentLoaded",()=>{if(el("tourGroup")){changeGroup();changeNearGroup();render();changeReturn();renderPlans();loadLocalRoadEvents()}});
})();
