"use strict";
(function(){
const el=id=>document.getElementById(id);const state={target:null,stops:[]};
const esc=v=>String(v==null?"":v).replace(/[&<>"\x27]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\x27":"&#39;"}[c]));
const valid=p=>p&&p.lat!=null&&p.lng!=null&&Number.isFinite(+p.lat)&&Number.isFinite(+p.lng);
const label=p=>valid(p)?p.lat+","+p.lng:(p.navQuery||p.name||"");
const dKm=(a,b)=>{const r=x=>x*Math.PI/180,dl=r(b.lat-a.lat),do_=r(b.lng-a.lng),v=Math.sin(dl/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(do_/2)**2;return 12742*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
const azimuth=(a,b)=>{const r=x=>x*Math.PI/180,y=Math.sin(r(b.lng-a.lng))*Math.cos(r(b.lat)),x=Math.cos(r(a.lat))*Math.sin(r(b.lat))-Math.sin(r(a.lat))*Math.cos(r(b.lat))*Math.cos(r(b.lng-a.lng));return(Math.atan2(y,x)*180/Math.PI+360)%360};
const groupOptions=[["","すべて"],["cafe","カフェ・飲食"],["shop","バイクショップ"],["rest","ライダー休憩所"],["lodging","ライダー向け宿泊"],["service","整備・サービス"],["community","交流スポット"]];
const origin=()=>typeof origins!=="undefined"?origins.ride:null;
function spots(){const data=window.APP_DATA||{};return [...(data.roads||[]).map(x=>({...x,tourGroup:"road"})),...(data.landmarks||[]).map(x=>({...x,tourGroup:x.level==="A"?"A":"B"})),...(window.RIDERS_CAFES||[]).filter(x=>(x.publish!==false||x.testOnly)&&(x.gachaDestinationEligible===true||(x.gachaDestinationEligible!==false&&["cafe","food","rest","community"].includes(x.spotCategory||"cafe")))).map(x=>({...x,tourGroup:"riders"}))].filter(valid)}
function changeGroup(){const group=el("tourGroup").value;const options=group==="riders"?groupOptions:[["","すべて"]];el("tourCategory").innerHTML=options.map(x=>"<option value="+JSON.stringify(x[0])+">"+esc(x[1])+"</option>").join("")}
function search(){const from=origin();if(!from){alert("先に出発地点を設定してください");return}const km=+el("tourDistance").value,tol=+el("tourTolerance").value;if(!(km>0&&km<=1000&&tol>=0&&tol<=300)){alert("距離の入力値を確認してください");return}const compass={north:0,east:90,south:180,west:270},dir=el("tourDirection").value,group=el("tourGroup").value,cat=el("tourCategory").value;const list=spots().filter(x=>group==="all"||x.tourGroup===group).filter(x=>group!=="riders"||!cat||(x.spotCategory||"cafe")===cat).map(x=>({...x,tourKm:dKm(from,x),tourAz:azimuth(from,x)})).filter(x=>x.tourKm>=Math.max(0,km-tol)&&x.tourKm<=km+tol).filter(x=>dir==="all"||Math.abs((x.tourAz-compass[dir]+540)%360-180)<=33.75).sort((a,b)=>Math.abs(a.tourKm-km)-Math.abs(b.tourKm-km));window.tourCandidates=list;el("tourCandidates").innerHTML="<div class=\"panel full\">検索結果 "+list.length+"件（直線"+Math.max(0,km-tol)+"〜"+(km+tol)+"km）</div>"+list.slice(0,100).map((x,i)=>"<div class=\"spot-card\"><div class=\"spot-info\"><h3>"+esc(x.name)+"</h3><div class=\"meta\">"+esc(x.prefecture||"")+" / 直線"+x.tourKm.toFixed(1)+"km</div></div><div class=\"actions\"><button class=\"soft\" onclick=\"tourChoose("+i+")\">🎯 目標にする</button></div></div>").join("")+(list.length>100?"<p>上位100件を表示。距離・方角で絞り込んでください。</p>":"")}
function choose(i){const x=window.tourCandidates?.[i];if(!x)return;state.target={name:x.name,lat:x.lat,lng:x.lng,navQuery:x.navQuery||""};state.stops=[];render();nearby()}
function nearby(){if(!state.target)return alert("目標地点を選択してください");const km=+el("tourRadius").value;if(!(km>=0&&km<=300))return alert("寄り道半径を確認してください");const list=spots().filter(x=>dKm(x,state.target)<=km&&!(x.name===state.target.name&&x.lat===state.target.lat&&x.lng===state.target.lng)).sort((a,b)=>dKm(a,state.target)-dKm(b,state.target));window.tourNearList=list;el("tourNearby").innerHTML="<div class=\"panel full\">目標周辺 "+list.length+"件（直線"+km+"km以内）</div>"+list.slice(0,100).map((x,i)=>"<div class=\"spot-card\"><div class=\"spot-info\"><h3>"+esc(x.name)+"</h3></div><button class=\"soft\" onclick=\"tourAddNearby("+i+")\">＋寄り道</button></div>").join("")}
function add(x){if(!state.target)return alert("目標地点を選択してください");if(state.stops.length>=2)return alert("寄り道は最大2地点です");state.stops.push(x);render()}
function addNearby(i){const x=window.tourNearList?.[i];if(x)add({name:x.name,lat:x.lat,lng:x.lng,navQuery:x.navQuery||""})}
function addFree(){const name=el("tourFreeName").value.trim();if(!name)return alert("場所名または住所を入力してください");add({name,navQuery:name});el("tourFreeName").value=""}
function remove(i){state.stops.splice(i,1);render()}
function render(){el("tourPlanState").innerHTML="<div>🎯 目標："+esc(state.target?.name||"未選択")+"</div>"+state.stops.map((x,i)=>"<div>☕ 寄り道"+(i+1)+"："+esc(x.name)+" <button class=\"soft\" onclick=\"tourRemove("+i+")\">削除</button></div>").join("")+"<div class=\"meta\">中間経由地 "+(state.target?1+state.stops.length:0)+"/3</div>"}
function changeReturn(){el("tourReturnExtra").hidden=el("tourReturnSame").checked}
function openMaps(){if(!origin()||!state.target)return alert("出発地点と目標地点を設定してください");const ret=el("tourReturnSame").checked?origin():(typeof origins!=="undefined"&&origins.tourReturn)||(()=>{const v=el("tourReturnName").value.trim();return v?{name:v,navQuery:v}:null})();if(!ret)return alert("帰着地点を指定してください");const params=new URLSearchParams({api:"1",origin:label(origin()),destination:label(ret),waypoints:[state.target,...state.stops].map(label).join("|"),travelmode:"driving"});if(el("tourVehicle").value==="125")params.set("avoid","highways,tolls");const url="https://www.google.com/maps/dir/?"+params;if(url.length>2048)return alert("地名が長すぎるためGoogleマップへ渡せません");window.open(url,"_blank","noopener")}
window.tourGroupChanged=changeGroup;window.tourSearch=search;window.tourChoose=choose;window.tourSearchNearby=nearby;window.tourAddNearby=addNearby;window.tourAddFree=addFree;window.tourRemove=remove;window.tourReturnChanged=changeReturn;window.tourOpenMaps=openMaps;
document.addEventListener("DOMContentLoaded",()=>{if(el("tourGroup")){changeGroup();render();changeReturn()}});
})();
